export const styles: { [key: string]: React.CSSProperties } = {
  background: {
    position: "fixed",
    top: 0,
    left: 0,
    width: "100vw",
    height: "100vh",
    background: "linear-gradient(135deg, #8e2de2, #ff6a95)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
    boxSizing: "border-box",
  },
  container: {
    backgroundColor: "rgba(255, 255, 255, 0.15)",
    borderRadius: 12,
    maxWidth: 700,
    width: "100%",
    padding: 24,
    color: "white",
    boxShadow: "0 8px 16px rgba(0,0,0,0.3)",
    display: "flex",
    flexDirection: "column",
  },
  title: {
    fontWeight: "700",
    fontSize: 22,
    textAlign: "center",
    marginBottom: 16,
  },
  input: {
    backgroundColor: "transparent",
    border: "1px solid rgba(255, 255, 255, 0.7)",
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
    fontSize: 16,
    color: "white",
    outline: "none",
  },
  button: {
    border: "none",
    borderRadius: 8,
    color: "#fff",
    padding: 14,
    fontWeight: "bold",
    cursor: "pointer",
    width: "100%",
    fontSize: 16,
    transition: "background-color 0.3s ease",
  },
};