import { CSSProperties } from "react";

export const styles: { [key: string]: CSSProperties } = {
  container: {
    minHeight: "100vh",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    background: "linear-gradient(135deg, #8e2de2, #ff6a95)",
    padding: "20px",
  },
  form: {
    maxWidth: 360,
    width: "100%",
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    padding: "30px 25px",
    borderRadius: 12,
    boxShadow: "0 8px 16px rgba(0,0,0,0.25)",
    display: "flex",
    flexDirection: "column",
    gap: 16,
  },
  title: {
    fontFamily: "'Pacifico', cursive",
    fontSize: "2.5rem",
    color: "#8e2de2",
    textAlign: "center",
    marginBottom: 10,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "10px",
  },
  logo: {
    width: 100,
    height: 100,
    borderRadius: 8,
  },
  errorText: {
    color: "red",
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 8,
  },
  input: {
    padding: "12px 15px",
    fontSize: 16,
    borderRadius: 8,
    border: "1.5px solid #ccc",
    outlineColor: "#8e2de2",
  },
  primaryButton: {
    padding: "12px",
    fontSize: 18,
    backgroundColor: "#8e2de2",
    color: "#fff",
    border: "none",
    borderRadius: 8,
    cursor: "pointer",
    transition: "background-color 0.3s",
  },
  secondaryButton: {
    padding: "12px",
    fontSize: 18,
    backgroundColor: "#ff6a95",
    color: "#fff",
    border: "none",
    borderRadius: 8,
    cursor: "pointer",
    transition: "background-color 0.3s",
  },
};
